spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: LJR199308
    url: jdbc:mysql://localhost:3306/wan_da_xin_prod?useUnicode=true&characterEncoding=utf8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 车管家管理平台
  try-host: http://localhost:${server.port}