spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: LJR199308
    url: jdbc:mysql://localhost:3306/wan_da_xin_prod?useUnicode=true&characterEncoding=utf8
